# Generated by Django 5.0 on 2023-12-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_upload', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_paths', models.JSONField()),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_upload.uploadedfile')),
            ],
        ),
    ]
